[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oscutils"
version = "0.0.0"
requires-python = ">=3.8"
dependencies = [
    "pandas>=1.4",
]

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"oscutils.data" = [
    "proteome_discoverer/Payne_Organoids_AnnotationProteinGroups.txt",
    "proteome_discoverer/Payne_Organoids_PathwayProteinGroups.txt",
    "proteome_discoverer/Payne_Organoids_ProteinGroups.txt",
    "proteome_discoverer/Payne_Organoids_Proteins.txt",
    "proteome_discoverer/Payne_Organoids_StudyInformation.txt",
    "metamorpheus/Task1-SearchTask/AllQuantifiedProteinGroups.tsv",
]
